# Generated by Django 4.1.2 on 2022-10-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp02", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="board_idx",),
    ]
